src/api/urls.py
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions, routers

from api.views import (BrandViewSet, CategoryViewSet, CityViewSet,
                       CustomerCreate, CustomerDelete, CustomerListAll,
                       CustomerListOne, CustomerUpdate,
                       ProducingCountryViewSet, ProductCreate, ProductDelete,
                       ProductListAll, ProductListOne, ProductUpdate)

app_name = "api"
router = routers.DefaultRouter()
router.register("category", CategoryViewSet)
router.register("country", ProducingCountryViewSet)
router.register("brand", BrandViewSet)
router.register("city", CityViewSet)

schema_view = get_schema_view(
    openapi.Info(
        title="Sonata Textile API",
        default_version="v1.0",
        description="API for passing questions",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="admin@admin.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path("", include(router.urls)),
    path("auth/", include("djoser.urls.jwt")),
    path("docs/", schema_view.with_ui("swagger", cache_timeout=0), name="swagger_docs"),
    path("customers/", CustomerListAll.as_view(), name="customers_all"),
    path("customers/<int:pk>/", CustomerListOne.as_view(), name="customer_one"),
    path("customers/create/", CustomerCreate.as_view(), name="customer_create"),
    path("customers/update/<int:pk>/", CustomerUpdate.as_view(), name="customer_update"),
    path("customers/delete/<int:pk>/", CustomerDelete.as_view(), name="customer_delete"),
    path("products/", ProductListAll.as_view(), name="products_all"),
    path("products/<int:pk>/", ProductListOne.as_view(), name="product_one"),
    path("products/create/", ProductCreate.as_view(), name="product_create"),
    path("products/update/<int:pk>/", ProductUpdate.as_view(), name="product_update"),
    path("products/delete/<int:pk>/", ProductDelete.as_view(), name="product_delete"),
]

src/order/urls.py
from django.urls import path

from .views import ShowBasketView, add_to_cart, cart_generate, order_view

app_name = "order"
urlpatterns = [
    path("add_to_cart/", add_to_cart, name="add_to_cart"),
    path("basket/", ShowBasketView.as_view(), name="show_basket"),
    path("generate-cart/", cart_generate, name="cart_generate"),
    path("decor/", order_view, name="order_view"),
]

src/order/models.py
from random import choice, randint

from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _

from products.models import Product


class Cart(models.Model):
    class Meta:
        verbose_name = _("Кошик")
        verbose_name_plural = _("Кошик")

    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    items = models.ManyToManyField(Product, through="CartItem")

    def __str__(self):
        return f"{self.user}"


class CartItem(models.Model):
    class Meta:
        verbose_name = _("Інформація кошику")
        verbose_name_plural = _("Інформація кошику")

    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name=_("Товар"))
    quantity = models.PositiveIntegerField(_("Кількість"), default=1)

    def __str__(self):
        return f"{self.cart} - {self.product}"

    @classmethod
    def generate_instances(cls):
        users = get_user_model().objects.all()
        products = Product.objects.all()
        for user in users:
            try:
                cart = Cart.objects.get(user=user)
                all_products = CartItem.objects.filter(cart=cart)
            except Cart.DoesNotExist:
                cart = Cart.objects.create(user=user)
                all_products = []
            if not all_products:
                for i in range(3):
                    product = choice(products)
                    quantity = randint(1, 5)
                    cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)

                    if not created:
                        cart_item.quantity += quantity
                        cart_item.save()


class Order(models.Model):
    class Meta:
        verbose_name = _("Замовлення")
        verbose_name_plural = _("Замовлення")

    class DELIVERY_CHOICES(models.IntegerChoices):
        NEW_POST = 0, "Нова пошта"
        UKRAINIAN_POST = 1, "Укрпошта"

    class PAYMENT_CHOICES(models.IntegerChoices):
        CASH = 0, "Оплата при доставці"
        CARD = 1, "Переказ на карту"

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    cart = models.TextField(verbose_name=_("Кошик"))
    delivery_method = models.PositiveSmallIntegerField(_("Спосіб доставки"), choices=DELIVERY_CHOICES.choices)
    payment_method = models.PositiveSmallIntegerField(
        _("Спосіб оплати"),
        choices=PAYMENT_CHOICES.choices,
        default=PAYMENT_CHOICES.CASH,
    )
    city = models.ForeignKey(to="order.City", on_delete=models.CASCADE, verbose_name=_("Місто"))
    branch_address = models.CharField(_("Адреса відділення"), max_length=255)

    def __str__(self):
        return f"{self.pk} - {self.user}"


class City(models.Model):
    class Meta:
        verbose_name = _("Місто")
        verbose_name_plural = _("Міста")

    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return f"{self.name}"

src/order/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from order.models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["delivery_method", "payment_method", "city", "branch_address"]

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user

        if user.social_auth.filter(provider="google-oauth2").exists():
            user_info_dict = {
                "first_name": user.first_name,
                "last_name": user.last_name,
                "phone_number": user.phone_number,
            }
            translate_fields = {"first_name": "Ім'я", "last_name": "Прізвище", "phone_number": "Номер телефону"}
            filtered_user_info = {key: value for key, value in user_info_dict.items() if value is None}
            for key in filtered_user_info:
                self.fields[key] = forms.CharField(label=_(translate_fields[key]), max_length=80, required=True)

        for field_name in self.fields:
            self.fields[field_name].required = True

src/order/views.py
import json

from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render  # NOQA: F401
from django.views.generic import TemplateView

from config.settings.base import EMAIL_HOST_USER
from order.forms import OrderForm
from order.models import Cart, CartItem
from order.tasks import generate_cart
from products.models import Category, Product


def add_to_cart(request):
    return_dict = dict()
    data = request.POST
    product = get_object_or_404(Product, pk=data.get("product_id"))
    if data.get("update_quantity") and data.get("update_quantity") != "":
        quantity_action = data.get("update_quantity")
        cart = Cart.objects.get(user=request.user)
        cart_item = CartItem.objects.get(cart=cart, product=product)
        if quantity_action == "true":
            cart_item.quantity += 1
        elif quantity_action == "false":
            if cart_item.quantity > 1:
                cart_item.quantity -= 1
        cart_item.save()
    elif data.get("basket") == "true":
        cart, created = Cart.objects.get_or_create(user=request.user)
        cart_item, item_created = CartItem.objects.get_or_create(cart=cart, product=product)

        if not item_created:
            cart_item.quantity += 1
        else:
            cart_item.quantity = 1

        cart_item.save()
    else:
        cart = Cart.objects.get(user=request.user)
        CartItem.objects.get(cart=cart, product=product).delete()
    products_number = CartItem.objects.filter(cart=cart)
    total = 0
    total_price = 0
    return_dict["products_list"] = list()

    for cart_item_obj in products_number:
        total += cart_item_obj.quantity
        total_price += cart_item_obj.quantity * cart_item_obj.product.price.amount
        product_dict = dict()
        product_dict["id_product"] = cart_item_obj.product.id
        product_dict["image_product"] = cart_item_obj.product.avatar.url
        product_dict["article"] = cart_item_obj.product.article
        product_dict["name_product"] = cart_item_obj.product.name
        product_dict["price_product"] = cart_item_obj.product.price.amount
        product_dict["quantity"] = cart_item_obj.quantity
        return_dict["products_list"].append(product_dict)

    return_dict["products_number"] = total
    return_dict["products_total_price"] = total_price
    return JsonResponse(return_dict)


class ShowBasketView(TemplateView):
    template_name = "orders/basket.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = Cart.objects.get(user=self.request.user)
        products_cart = CartItem.objects.filter(cart=cart)
        context["categories"] = Category.objects.all()
        context["products_number"] = products_cart
        return context


def cart_generate(request):
    users = get_user_model().objects.all()
    products = Product.objects.all()
    if products and users:
        generate_cart.delay()
        return HttpResponse("Завдання розпочато")
    else:
        return HttpResponse("Спочатку треба згенерувати товари та користувачів!")


def order_view(request):
    categories = Category.objects.all()
    user = request.user
    if request.method == "POST":
        form = OrderForm(user, request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if user.social_auth.filter(provider="google-oauth2").exists():
                if "first_name" in form.cleaned_data:
                    user.first_name = form.cleaned_data["first_name"]
                if "last_name" in form.cleaned_data:
                    user.last_name = form.cleaned_data["last_name"]
                if "phone_number" in form.cleaned_data:
                    user.phone_number = form.cleaned_data["phone_number"]
                user.save()
            order.user = user
            cart = Cart.objects.get(user=user)
            order.cart = json.dumps(
                {
                    "items": [
                        {
                            "name": item.product.name,
                            "article": item.product.article,
                            "quantity": item.quantity,
                        }
                        for item in CartItem.objects.filter(cart=cart)
                    ]
                },
                ensure_ascii=False,
            )
            order.save()
            cart_item = CartItem.objects.filter(cart=cart)
            cart_item_list = []
            total_price = 0
            for item in cart_item:
                cart_item_list.append(f"{item.product.name}({item.product.article}) - {item.quantity} шт.")
                total_price += item.quantity * item.product.price.amount
            formatted_list = "\n".join(cart_item_list)
            send_mail(
                subject=f"Замовлення №{order.pk}!",
                message=f"Інформація про покупця:"
                f"\n\t1) Ім'я - {user.first_name}"
                f"\n\t2) Прізвище - {user.last_name}"
                f"\n\t3) Номер телефона - {user.phone_number}\n"
                f"Інформація про замовлення:"
                f"\n\t1) Спосіб доставки - {order.get_delivery_method_display()}"
                f"\n\t2) Спосіб оплати - {order.get_payment_method_display()}"
                f"\n\t3) Місто - {order.city}"
                f"\n\t4) Адреса відділення - {order.branch_address}\n"
                f"Товари:"
                f"\n{formatted_list}"
                f"\nДо сплати: {total_price}",
                from_email=EMAIL_HOST_USER,
                recipient_list=[
                    "drobotda598@gmail.com",
                ],
                fail_silently=False,
            )
            Cart.objects.filter(user=user).delete()
            return render(request, "orders/order.html", {"form": form, "success_modal": True})
    else:
        form = OrderForm(user)

    return render(request, "orders/order.html", {"form": form, "categories": categories})

src/templates/orders/order.html
{% extends "index.html" %}

{% block content %}
    <style>
        .log-in__form-outer {
            padding: 20px;
            border: 2px solid #3498db;
            border-radius: 10px;
            max-width: 400px;
            margin: auto;
        }

        .logo img {
            display: block;
            margin: 0 auto 20px;
        }

        .login-form__title {
            font-size: 1.5em;
            font-weight: bold;
            margin-bottom: 20px;
            text-align: center;
        }

        .form-action button {
            display: block;
            width: 100%;
            padding: 10px;
            background-color: #2ecc71;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        .login-form__form-bottom a {
            color: #3498db;
            text-decoration: none;
        }

        .form-field {
            margin-bottom: 15px;
        }

        .form-field label {
            display: block;
            margin-bottom: 5px;
        }

        .form-field input,
        .form-field select,
        .form-field textarea {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
        }

        .sso__link svg {
            vertical-align: middle;
            margin-right: 10px;
        }

        .form-item label {
            display: block;
            margin-bottom: 5px;
        }

        .form-item input {
            width: 100%;
            box-sizing: border-box;
        }

        .modal {
            display: none;
            position: fixed;
            z-index: 1;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            overflow: auto;
            background-color: rgba(0, 0, 0, 0.4);
        }

        .modal-content {
            background-color: #fff;
            margin: 10% auto;
            padding: 20px;
            border: 1px solid #ddd;
            max-width: 400px;
            width: 80%;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .show {
            display: block;
        }

        #goToHome {
            display: inline-block;
            width: 100%;
            padding: 15px;
            background: linear-gradient(to right, #3498db, #6c5ce7);
            color: #fff;
            border: none;
            border-radius: 10px;
            cursor: pointer;
            font-size: 16px;
            font-weight: bold;
            text-align: center;
            text-decoration: none;
            transition: background 0.3s;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        }

        #goToHome:hover {
            background: linear-gradient(to right, #2980b9, #5a3db8);
            box-shadow: 0 6px 12px rgba(0, 0, 0, 0.3);
        }
    </style>

    <form class="log-in__form-outer" method="post" action="{% url 'order:order_view' %}" style="margin-top: 20px; margin-bottom: 40px;">
        {% csrf_token %}
        <div class="login-form__title">Оформлення замовлення</div>
        {% for field in form %}
            <div class="form-field">
                <label for="{{ field.id_for_label }}" style="margin-top: 10px;">{{ field.label }}</label>
                {{ field }}
            </div>
        {% endfor %}
        <div class="form-action">
            <button type="submit">Підтвердити замовлення</button>
        </div>
    </form>
    <div id="successModal" class="modal {% if success_modal %}show{% endif %}">
        <div class="modal-content">
            <p style="margin-left: 25px;">Ваше замовлення успішно оформлене!</p>
            <button id="goToHome">На головну</button>
        </div>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var goToHomeBtn = document.getElementById('goToHome');
            goToHomeBtn.onclick = function() {
                window.location.href = "{% url 'index' %}";
            };
        });
    </script>
{% endblock content %}