src/api/urls.py
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions, routers

from api.views import (BrandViewSet, CategoryViewSet, CityViewSet,
                       CustomerCreate, CustomerDelete, CustomerListAll,
                       CustomerListOne, CustomerUpdate,
                       ProducingCountryViewSet, ProductCreate, ProductDelete,
                       ProductListAll, ProductListOne, ProductUpdate)

app_name = "api"
router = routers.DefaultRouter()
router.register("category", CategoryViewSet)
router.register("country", ProducingCountryViewSet)
router.register("brand", BrandViewSet)
router.register("city", CityViewSet)

schema_view = get_schema_view(
    openapi.Info(
        title="Sonata Textile API",
        default_version="v1.0",
        description="API for passing questions",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="admin@admin.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path("", include(router.urls)),
    path("auth/", include("djoser.urls.jwt")),
    path("docs/", schema_view.with_ui("swagger", cache_timeout=0), name="swagger_docs"),
    path("customers/", CustomerListAll.as_view(), name="customers_all"),
    path("customers/<int:pk>/", CustomerListOne.as_view(), name="customer_one"),
    path("customers/create/", CustomerCreate.as_view(), name="customer_create"),
    path("customers/update/<int:pk>/", CustomerUpdate.as_view(), name="customer_update"),
    path("customers/delete/<int:pk>/", CustomerDelete.as_view(), name="customer_delete"),
    path("products/", ProductListAll.as_view(), name="products_all"),
    path("products/<int:pk>/", ProductListOne.as_view(), name="product_one"),
    path("products/create/", ProductCreate.as_view(), name="product_create"),
    path("products/update/<int:pk>/", ProductUpdate.as_view(), name="product_update"),
    path("products/delete/<int:pk>/", ProductDelete.as_view(), name="product_delete"),
]

src/core/urls.py
from django.urls import path

from core.views import (AboutUsView, AllCategoriesView, ContactsView,
                        DeliveryView, IndexView, PartnersView, UserLogin,
                        UserLogout)

app_name = "core"
urlpatterns = [
    path("index/", IndexView.as_view(), name="index"),
    path("about_us/", AboutUsView.as_view(), name="about_us"),
    path("delivery/", DeliveryView.as_view(), name="delivery"),
    path("categories/", AllCategoriesView.as_view(), name="all_categories"),
    path("login/", UserLogin.as_view(), name="login"),
    path("logout/", UserLogout.as_view(), name="logout"),
    path("contacts/", ContactsView.as_view(), name="contacts"),
    path("partners/", PartnersView.as_view(), name="partners"),
]

src/products/urls.py
from django.urls import path

from products.views import (ProductDetailView, ProductListView,
                            ProductSearchListView, brand_generate,
                            categories_generate, material_generate,
                            producing_country_generate, product_generate)

app_name = "products"
urlpatterns = [
    path("category/<int:pk>/", ProductListView.as_view(), name="category_products"),
    path("product/<int:pk>/", ProductDetailView.as_view(), name="product_info"),
    path("search/", ProductSearchListView.as_view(), name="search_product"),
    path("generate-category/<int:number>/", categories_generate, name="categories_generate"),
    path("generate-country/<int:number>/", producing_country_generate, name="producing_country_generate"),
    path("generate-brand/<int:number>/", brand_generate, name="brand_generate"),
    path("generate-material/<int:number>/", material_generate, name="material_generate"),
    path("generate/<int:number>/", product_generate, name="product_generate"),
]

src/products/models.py
from random import choice, randint

import requests
from django.core.files.base import ContentFile
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from djmoney.models.fields import MoneyField
from faker import Faker


class Product(models.Model):
    class Meta:
        verbose_name = _("Товар")
        verbose_name_plural = _("Товари")

    article = models.IntegerField(_("Артикул"), unique=True)
    avatar = models.ImageField(_("Зображення"), upload_to="img/products", null=True, blank=True)
    name = models.CharField(_("Назва"), max_length=250)
    category = models.ForeignKey(
        to="products.Category",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name=_("Категорія"),
    )
    brand = models.ForeignKey(
        to="products.Brand",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name=_("Бренд"),
    )
    price = MoneyField(_("Ціна"), max_digits=10, decimal_places=2, default_currency="UAH")
    size = models.CharField(_("Розмір"), max_length=50)
    material = models.ForeignKey(
        to="products.Material",
        on_delete=models.CASCADE,
        verbose_name=_("Матеірал"),
        null=True,
        blank=True,
    )
    producing_country = models.ForeignKey(
        to="products.ProducingCountry",
        on_delete=models.CASCADE,
        verbose_name=_("Країна виробництва"),
        null=True,
        blank=True,
    )
    availability = models.BooleanField(_("Наявність"), default=True)
    hit_sale = models.BooleanField(_("Хіт продаж"), default=False)
    description = models.TextField(_("Опис"), null=True, blank=True)

    def __str__(self):
        return f"{self.name} ({self.article})"

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()
        categories = Category.objects.all()
        brands = Brand.objects.all()
        materials = Material.objects.all()
        producing_countries = ProducingCountry.objects.all()

        for i in range(count):
            unique_article_generated = False
            while not unique_article_generated:
                article = randint(100, 9999)
                try:
                    Product.objects.get(article=article)
                except Product.DoesNotExist:
                    unique_article_generated = True

            product = Product.objects.create(
                article=article,
                name=faker.word(),
                category=choice(categories),
                brand=choice(brands),
                price=faker.random_int(min=100, max=3000),
                size=faker.random_element(elements=("S", "M", "L", "XL")),
                material=choice(materials),
                producing_country=choice(producing_countries),
                availability=faker.boolean(),
                hit_sale=faker.boolean(),
                description=faker.text(),
            )
            image_url = "https://picsum.photos/500/500"
            image_content = requests.get(image_url).content
            image_name = f"product_{timezone.now().strftime('%Y%m%d%H%M%S')}.jpg"

            product.avatar.save(image_name, ContentFile(image_content))


class Category(models.Model):
    class Meta:
        verbose_name = _("Категорія")
        verbose_name_plural = _("Категорії")

    name = models.CharField(max_length=100, unique=True)
    image = models.ImageField(upload_to="img/categories", null=True, blank=True)

    def __str__(self):
        return f"{self.name}"

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()
        for i in range(count):
            unique_name_generated = False
            while not unique_name_generated:
                name = faker.word()
                try:
                    Category.objects.get(name=name)
                except Category.DoesNotExist:
                    unique_name_generated = True

            category = Category(name=name)
            image_url = "https://picsum.photos/500/500"
            image_content = requests.get(image_url).content
            image_name = f"category_{timezone.now().strftime('%Y%m%d%H%M%S')}.jpg"

            category.image.save(image_name, ContentFile(image_content))


class ProducingCountry(models.Model):
    class Meta:
        verbose_name = _("Країна виробництва")
        verbose_name_plural = _("Країни виробництва")

    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return f"{self.name}"

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()
        for i in range(count):
            unique_name_generated = False
            while not unique_name_generated:
                name = faker.word()
                try:
                    ProducingCountry.objects.get(name=name)
                except ProducingCountry.DoesNotExist:
                    unique_name_generated = True

            ProducingCountry.objects.create(
                name=name,
            )


class Brand(models.Model):
    class Meta:
        verbose_name = _("Бренд")
        verbose_name_plural = _("Бренди")

    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return f"{self.name}"

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()
        for i in range(count):
            unique_name_generated = False
            while not unique_name_generated:
                name = faker.word()
                try:
                    Brand.objects.get(name=name)
                except Brand.DoesNotExist:
                    unique_name_generated = True

            Brand.objects.create(
                name=name,
            )


class Material(models.Model):
    class Meta:
        verbose_name = _("Матеріал")
        verbose_name_plural = _("Матеріали")

    name = models.CharField(max_length=70, unique=True)

    def __str__(self):
        return f"{self.name}"

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()
        for i in range(count):
            unique_name_generated = False
            while not unique_name_generated:
                name = faker.word()
                try:
                    Material.objects.get(name=name)
                except Material.DoesNotExist:
                    unique_name_generated = True

            Material.objects.create(
                name=name,
            )

src/products/views.py
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render  # NOQA: F401
from django.views.generic import DetailView, ListView, TemplateView

from products.models import (Brand, Category, Material, ProducingCountry,
                             Product)
from products.tasks import (generate_brand, generate_categories,
                            generate_material, generate_producing_country,
                            generate_product)


class ProductListView(TemplateView):
    model = Category
    template_name = "category/products.html"

    def get(self, request, *args, **kwargs):
        material_filter = request.GET.get("material")
        price_filter = request.GET.get("price")
        category = self.model.objects.get(pk=self.kwargs["pk"])
        if material_filter and price_filter:
            if price_filter == "0":
                products = Product.objects.filter(Q(category=category) & Q(material__pk=material_filter)).order_by(
                    "-price"
                )
            else:
                products = Product.objects.filter(Q(category=category) & Q(material__pk=material_filter)).order_by(
                    "price"
                )
        elif material_filter:
            products = Product.objects.filter(Q(category=category) & Q(material__pk=material_filter))
        elif price_filter:
            if price_filter == "0":
                products = Product.objects.filter(category=category).order_by("-price")
            else:
                products = Product.objects.filter(category=category).order_by("price")
        else:
            products = Product.objects.filter(category=category)
        context = {
            "products": products,
            "materials": Material.objects.all(),
            "categories": Category.objects.all(),
            "material_filter": material_filter,
            "price_filter": price_filter,
            "category": category,
        }
        if material_filter:
            context["material"] = Material.objects.get(id=material_filter)
        return render(request, self.template_name, context)


class ProductDetailView(DetailView):
    model = Product
    template_name = "product/product_info.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        context["products"] = Product.objects.filter(hit_sale=True)
        return context


class ProductSearchListView(ListView):
    model = Product
    template_name = "product/search_product.html"
    context_object_name = "products"

    def get_queryset(self):
        queryset = super().get_queryset()
        search_text = self.request.GET.get("search_text", "")

        if search_text:
            name_filter = Q(name__iregex=rf".*{search_text}.*")
            article_filter = Q(article__icontains=str(search_text))
            queryset = queryset.filter(name_filter | article_filter)

        return queryset


def categories_generate(request, number):
    generate_categories.delay(int(number))
    return HttpResponse("Завдання розпочато")


def producing_country_generate(request, number):
    generate_producing_country.delay(int(number))
    return HttpResponse("Завдання розпочато")


def brand_generate(request, number):
    generate_brand.delay(int(number))
    return HttpResponse("Завдання розпочато")


def material_generate(request, number):
    generate_material.delay(int(number))
    return HttpResponse("Завдання розпочато")


def product_generate(request, number):
    categories = Category.objects.all()
    brands = Brand.objects.all()
    materials = Material.objects.all()
    producing_countries = ProducingCountry.objects.all()
    if categories and brands and materials and producing_countries:
        generate_product.delay(int(number))
        return HttpResponse("Завдання розпочато")
    else:
        return HttpResponse("Спочатку треба згенерувати категорії, бренди, країни виробництва та матеріали!")

src/templates/category/index_category.html
{% extends "index.html" %}
{% block content %}
    <h1 style="text-align: center; margin-bottom: 25px; margin-top: 25px;">Каталог</h1>
    <div class="row">
        {% for category in categories %}
            <div class="col-md-3 mb-3">
                <a href="{% url 'products:category_products' category.id %}" style="text-decoration: none;">
                    <div class="card" style="width: 100%;">
                        <img src="{{ category.image.url }}" class="card-img-top" alt="Фото категорії"
                             style="width: 100%; height: 270px; object-fit: cover;">
                        <div class="card-body">
                            <h5 class="card-title"
                                style="font-weight: bold; font-size: 1.20rem; text-align: center; ">{{ category.name }}</h5>
                        </div>
                    </div>
                </a>
            </div>
            {% if forloop.counter|divisibleby:4 and not forloop.last %}</div>
                <div class="row">{% endif %}
        {% endfor %}
        </div>
{% endblock content %}

src/templates/category/products.html
{% extends "index.html" %}
{% block content %}
    <style>
        #addedText {
            position: absolute;
            left: 0;
            top: 89%;
            display: none;
            margin-left: 26px;
            color: white;
            background-color: limegreen;
            padding: 8px 13px;
            border-radius: 5px;
        }
    </style>
    <div class="container" style="margin-top: 40px; margin-bottom: 20px;">
        <div class="row">
            <div class="col-md-3" style="width: 20%;">
                <h5 style="color: darkgreen; font-weight: bold; font-style: italic;">Фільтр за матеріалом:</h5>
                <ul class="list-group">
                    {% for material in materials %}
                        {% if price_filter == None %}
                            <li class="list-group-item"><a href="?material={{ material.pk }}"
                                                           style="text-decoration: none; color: black;">{{ material.name }}</a>
                            </li>
                        {% else %}
                            <li class="list-group-item"><a href="?price={{ price_filter }}&material={{ material.pk }}"
                                                           style="text-decoration: none; color: black;">{{ material.name }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
                <h5 style="color: darkgreen; font-weight: bold; font-style: italic; margin-top: 20px;">Фільтр за
                    ціною:</h5>
                <ul class="list-group">
                    {% if material_filter == None %}
                        <li class="list-group-item"><a href="?price=1"
                                                       style="text-decoration: none; color: black;">Від дешевших до
                            дорогих</a>
                        </li>
                        <li class="list-group-item"><a href="?price=0"
                                                       style="text-decoration: none; color: black;">Від дорогих до
                            дешевших</a>
                        </li>
                    {% else %}
                        <li class="list-group-item"><a href="?material={{ material_filter }}&price=1"
                                                       style="text-decoration: none; color: black;">Від дешевших до
                            дорогих</a>
                        </li>
                        <li class="list-group-item"><a href="?material={{ material_filter }}&price=0"
                                                       style="text-decoration: none; color: black;">Від дорогих до
                            дешевших</a>
                        </li>
                    {% endif %}
                </ul>
                {% if material_filter or price_filter %}
                    <h5 style="color: darkgreen; font-weight: bold; font-style: italic; margin-top: 20px;">Застосовані
                        фільтри</h5>
                    {% if material_filter and price_filter %}
                        <p style="color: black; margin-left: 5px; font-size: 1.1rem"><strong>Матеріал</strong>
                            - {{ material.name }}</p>
                        {% if price_filter == "0" %}
                            <p style="color: black; margin-left: 5px; font-size: 1.1rem; margin-top: -10px;"><strong>Ціна</strong>
                                - за спаданням</p>
                        {% else %}
                            <p style="color: black; margin-left: 5px; font-size: 1.1rem; margin-top: -10px;"><strong>Ціна</strong>
                                - за зростанням</p>
                        {% endif %}
                    {% elif material_filter %}
                        <p style="color: black; margin-left: 5px; font-size: 1.1rem"><strong>Матеріал</strong>
                            - {{ material.name }}</p>
                    {% else %}
                        {% if price_filter == "0" %}
                            <p style="color: black; margin-left: 5px; font-size: 1.1rem;"><strong>Ціна</strong>
                                - за спаданням</p>
                        {% else %}
                            <p style="color: black; margin-left: 5px; font-size: 1.1rem;"><strong>Ціна</strong>
                                - за зростанням</p>
                        {% endif %}
                    {% endif %}
                    <a class="btn btn-outline-secondary" style="margin-left: 20px;"
                       href="{% url 'products:category_products' category.id %}">Видалити
                        фільтри</a>
                {% endif %}
            </div>

            <div class="col-md-9">
                <div class="row">
                    {% for product in products %}
                        <div class="col-md-4 mb-3" style="width: 25%;">
                            <a href="{% url 'products:product_info' product.id %}" style="text-decoration: none;">
                                <div class="card" style="width: 93%;">
                                    <img src="{{ product.avatar.url }}" class="card-img-top" alt="dfgdfg"
                                         style="width: 100%; height: 270px; object-fit: cover;">
                                    <div class="card-body">
                                        <h5 class="card-title"
                                            style="font-weight: bold; font-size: 1.20rem; color: black;">{{ product.name }}</h5>
                                        <p class="card-text"
                                           style="margin-bottom: 5px; font-style: italic; color: black;">
                                            Артикул: {{ product.article }}</p>
                                        <p class="card-text"
                                           style="margin-bottom: 5px; font-style: italic; color: black;">
                                            Ціна: {{ product.price.amount }} грн</p>
                                        <p class="card-text" style="font-style: italic; color: black;">
                                            Розмір: {{ product.size }}</p>
                                        {% if product.availability == True %}
                                            {% if user.is_authenticated %}
                                                <div class="d-flex justify-content-center">
                                                    <a id="addToCartBtn"
                                                       class="btn btn-outline-secondary add-to-cart-btn"
                                                       data-product_id="{{ product.id }}"
                                                       data-name="{{ product.name }}"
                                                       data-price="{{ product.price.amount }}"
                                                       style="margin-top: 10px;"
                                                    >Додати
                                                        в кошик</a>
                                                    <div id="addedText" class="green-line">Додано в кошик</div>
                                                </div>
                                            {% else %}
                                                <div class="d-flex justify-content-center">
                                                    <a href="{% url 'core:login' %}"
                                                       class="btn btn-outline-secondary "
                                                       style="margin-top: 10px;"
                                                    >Додати
                                                        в кошик</a>
                                                </div>
                                            {% endif %}
                                        {% else %}
                                            <p class="card-text"
                                               style="font-weight: bold; color: red; text-align: center; margin-bottom: 13px;">
                                                Немає в
                                                наявності</p>
                                        {% endif %}
                                    </div>
                                </div>
                            </a>
                        </div>
                        {% if forloop.counter|divisibleby:4 and not forloop.last %}
                            </div>
                            <div class="row">
                        {% endif %}
                    {% endfor %}
                    </div>
            </div>
        </div>
    </div>
{% endblock content %}